#!/usr/bin/env bash

LOGFILE=/var/log/klingelblink.log

PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export RACK_ENV=production
{
  cd $(dirname $0)
  exec ruby klingelblink.rb    
} >> $LOGFILE 2>&1
